import { KPIValue } from "./types";

export const mockKPIs: KPIValue[] = [
  {
    label: "Usuarios Totales",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "number",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "producto",
  },
  {
    label: "MAU",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "number",
    description: "Monthly Active Users: cuenta 1 usuario si se conecta al menos una vez al mes.",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "producto",
  },
  {
    label: "WAU",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "number",
    description: "Weekly Active Users: cuenta 1 usuario si se conecta en el periodo de la semana.",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "producto",
  },
  {
    label: "DAU",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "number",
    description: "Daily Active Users: cuenta 1 usuario si se conecta en las últimas 24h. Se restablece a las 00:00.",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "producto",
  },
  {
    label: "Engagement",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "percent",
    description: "Porcentaje de Engagement calculado como (DAU / MAU) * 100.",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "producto",
  },
  {
    label: "CAC",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    prefix: "€",
    format: "currency",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "ventas",
  },
  {
    label: "Churn Rate",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "percent",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "producto",
  },
  {
    label: "Horas Totales",
    current_value: 38.5,
    compare_value: 42.0,
    delta_abs: -3.5,
    delta_pct: -8.3,
    format: "hours",
    unit: "h",
    sparkline: [35, 38, 40, 41, 42, 39, 38.5],
    category: "proyecto",
  },
  {
    label: "Facturación",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    prefix: "€",
    format: "currency",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "ventas",
  },
  {
    label: "Beneficio",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    prefix: "€",
    format: "currency",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "operaciones",
  },
  {
    label: "MRR",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    prefix: "€",
    format: "currency",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "ventas",
  },
  {
    label: "Rentabilidad",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "percent",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "proyecto",
  },
  {
    label: "Margen Bruto",
    current_value: 0,
    compare_value: 0,
    delta_abs: 0,
    delta_pct: 0,
    format: "percent",
    sparkline: [0, 0, 0, 0, 0, 0, 0],
    category: "ventas",
  },
];

export const mockHoursByCategoryByOwner = {
  squirly: [
    { name: "Cristalización", hours: 10.0, color: "hsl(174, 72%, 52%)" },
    { name: "Diseño de proyecto", hours: 7.0, color: "hsl(262, 60%, 58%)" },
    { name: "Ejecución de proyecto", hours: 12.0, color: "hsl(38, 92%, 56%)" },
    { name: "Reuniones de equipo", hours: 5.0, color: "hsl(0, 72%, 56%)" },
    { name: "Visitas comerciales", hours: 3.0, color: "hsl(210, 60%, 56%)" },
    { name: "Formación", hours: 1.5, color: "hsl(320, 65%, 60%)" },
  ],
  quique: [
    { name: "Cristalización", hours: 6.0, color: "hsl(174, 72%, 52%)" },
    { name: "Diseño de proyecto", hours: 4.5, color: "hsl(262, 60%, 58%)" },
    { name: "Ejecución de proyecto", hours: 8.0, color: "hsl(38, 92%, 56%)" },
    { name: "Reuniones de equipo", hours: 3.0, color: "hsl(0, 72%, 56%)" },
    { name: "Visitas comerciales", hours: 2.5, color: "hsl(210, 60%, 56%)" },
    { name: "Formación", hours: 1.0, color: "hsl(320, 65%, 60%)" },
  ],
  adri: [
    { name: "Cristalización", hours: 4.0, color: "hsl(174, 72%, 52%)" },
    { name: "Diseño de proyecto", hours: 3.5, color: "hsl(262, 60%, 58%)" },
    { name: "Ejecución de proyecto", hours: 6.0, color: "hsl(38, 92%, 56%)" },
    { name: "Reuniones de equipo", hours: 2.5, color: "hsl(0, 72%, 56%)" },
    { name: "Visitas comerciales", hours: 1.5, color: "hsl(210, 60%, 56%)" },
    { name: "Formación", hours: 0.8, color: "hsl(320, 65%, 60%)" },
  ],
} as const;

export const mockRevenueWeekly = [
  { day: "Lun", current: 2800, previous: 2200 },
  { day: "Mar", current: 3200, previous: 2800 },
  { day: "Mié", current: 2600, previous: 2100 },
  { day: "Jue", current: 3100, previous: 2400 },
  { day: "Vie", current: 3800, previous: 3200 },
  { day: "Sáb", current: 1800, previous: 1500 },
  { day: "Dom", current: 1150, previous: 1000 },
];

export const mockChurnData = [
  { month: "Oct", rate: 4.2 },
  { month: "Nov", rate: 3.8 },
  { month: "Dic", rate: 3.5 },
  { month: "Ene", rate: 3.2 },
  { month: "Feb", rate: 3.4 },
  { month: "Mar", rate: 2.1 },
];

export const mockOperationsData = [
  { date: "01 Mar", cv: 12, lv: 5, eventos: 1 },
  { date: "02 Mar", cv: 9, lv: 4, eventos: 0 },
  { date: "03 Mar", cv: 14, lv: 6, eventos: 2 },
  { date: "04 Mar", cv: 11, lv: 3, eventos: 0 },
  { date: "05 Mar", cv: 16, lv: 7, eventos: 1 },
  { date: "06 Mar", cv: 15, lv: 5, eventos: 1 },
  { date: "07 Mar", cv: 12, lv: 4, eventos: 0 },
];

export const mockMetaAds = [
  { day: "Lun", spend: 120, conversions: 3, clicks: 85 },
  { day: "Mar", spend: 145, conversions: 4, clicks: 102 },
  { day: "Mié", spend: 98, conversions: 2, clicks: 72 },
  { day: "Jue", spend: 160, conversions: 5, clicks: 118 },
  { day: "Vie", spend: 175, conversions: 4, clicks: 130 },
  { day: "Sáb", spend: 80, conversions: 2, clicks: 58 },
  { day: "Dom", spend: 55, conversions: 1, clicks: 42 },
];
